# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '10.0'

target 'TIKI_TEST_PHAMANHUAN_Ver_1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TIKI_TEST_PHAMANHUAN_Ver_1

  target 'TIKI_TEST_PHAMANHUAN_Ver_1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TIKI_TEST_PHAMANHUAN_Ver_1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Alamofire', '~> 4.7'

end
